### ISSUE TITLE
Registrants data not available for some challenges 

### ISSUE THREAD

**Issue by sushilshinde** [topcoder-platform/challenge-api#201] opened 2020-06-30 01:48 UTC
https://github.com/topcoder-platform/community-app/issues/4608

**Comment by SathyaJayabal** [comment] 2020-07-01 08:16
https://github.com/topcoder-platform/community-app/issues/4608#issuecomment-652267820

**Comment by rootelement** [comment] 2020-07-01 20:48
@SathyaJayabal please test this again. The example challenges are now lining up since I've fixed the legacy resource processor

**Comment by SathyaJayabal** [comment] 2020-07-03 05:30
https://github.com/topcoder-platform/community-app/issues/4608#issuecomment-653338677

**Comment by mtwomey** [comment] 2020-07-14 03:40
James is testing fix now in dev.

**Comment by mtwomey** [comment] 2020-07-14 15:11
Working but there are some duplicate resources on challenges now, James is investigating.

**Comment by SathyaJayabal** [comment] 2020-07-15 07:03
Registrants not synced form v4 to v5. The duplicate resources issue has been fixed.
examples:
https://beta-community-app.topcoder.com/challenges/5f336776-80e2-45e2-89f8-0d9f37e34772?tab=registrants
https://www.topcoder.com/challenges/30132617?tab=registrants
https://beta-community-app.topcoder.com/challenges/9d796b12-1e6f-49b3-91df-2272f1044d32?tab=registrants
https://www.topcoder.com/challenges/30132988?tab=registrants

<img width="1440" alt="Screenshot 2020-07-15 at 12 30 52 PM" src="https://user-images.githubusercontent.com/58783823/87513959-24eb8e80-c697-11ea-8195-8712db826161.png">
<img width="1440" alt="Screenshot 2020-07-15 at 12 32 03 PM" src="https://user-images.githubusercontent.com/58783823/87514010-3765c800-c697-11ea-97c6-620bd4df5432.png">

**Comment by SathyaJayabal** [comment] 2020-07-16 09:43
Registrants Sync issue:
@rootelement @lakshmiathreya @mtwomey 
Example challenge: 
https://beta-community-app.topcoder.com/challenges/9cc9ab57-d534-485f-8af2-f2c93c0775b4?tab=registrants
https://www.topcoder.com/challenges/30133097?tab=registrants
user:customeruser/appirio123

steps to reproduce:
1. Registrants are in sync between V4 and V5
2. Register to the above challenge from V5.
3. User shows up in registrants list in V5, but without registration date
<img width="1440" alt="Screenshot 2020-07-16 at 3 05 53 PM" src="https://user-images.githubusercontent.com/58783823/87656032-964e3e80-c776-11ea-8d8d-5ab9a1a6fb9b.png">
4. Check registrants list in V4. User shows up correctly with correct registration date
<img width="1440" alt="Screenshot 2020-07-16 at 3 06 30 PM" src="https://user-images.githubusercontent.com/58783823/87656122-b3830d00-c776-11ea-9618-b33e5db328b3.png">
5. Check registrants list in V5 again after a couple of mins(for sync). User added twice. 
<img width="1440" alt="Screenshot 2020-07-16 at 3 07 37 PM" src="https://user-images.githubusercontent.com/58783823/87656208-ceee1800-c776-11ea-8e49-2d0b6380c699.png">

**Comment by rootelement** [comment] 2020-07-20 13:30
This is fixed in dev and prod. Took a lot more tracking down than expected. Can be retested @SathyaJayabal

**Comment by SathyaJayabal** [comment] 2020-07-21 05:26
@rootelement 

1. Some challenges registrants count is wrong(when compared to list of registrants displayed below)
example:
https://beta-community-app.topcoder.com/challenges/339964ff-69fe-42f4-b97f-1f67e8561c75?tab=registrants
https://www.topcoder.com/challenges/30108180?tab=registrants

<img width="1440" alt="Screenshot 2020-07-21 at 10 15 26 AM" src="https://user-images.githubusercontent.com/58783823/88013902-38857200-cb3b-11ea-9b42-0de3e256890c.png">

2. Registrations from V4 not synced to V5 
example:
https://www.topcoder.com/challenges/30133461?tab=registrants
https://beta-community-app.topcoder.com/challenges/891de470-97ad-4b9b-9a46-75a485dabb0e?tab=registrants
Last two registrations from v4 are not displayed in V5.
 
3. Timezone of the registration date is incorrect V5, when user has registered from V4.
<img width="1440" alt="Screenshot 2020-07-21 at 10 27 28 AM" src="https://user-images.githubusercontent.com/58783823/88014741-4b00ab00-cb3d-11ea-90ed-533ec6ec5671.png">

**Comment by SathyaJayabal** [comment] 2020-07-21 05:34
4. Register from V5. Registrant immediately appears on the registrants list, but registrant count is not updated. This could be related to point 1 above.

**Comment by rootelement** [comment] 2020-07-21 14:18
1 & 2 were because the sync failed. I had to restart it. I'm really not sure about 3. Might want to open that in a separate issue and close this one.

**Comment by SathyaJayabal** [comment] 2020-07-21 15:18
@rootelement , yes 1 and 2 are fine now. Will track 3 separately.

**Comment by SathyaJayabal** [comment] 2020-07-28 06:56
@rootelement , registrations from v4 not synced to v5
<img width="1440" alt="Screenshot 2020-07-28 at 12 23 33 PM" src="https://user-images.githubusercontent.com/58783823/88629828-620b4400-d0cd-11ea-8f16-99245a352d64.png">

**Comment by rootelement** [comment] 2020-07-28 21:07
This looks good now. The only things I see off now are:
 - Prizes for v4 challenges that aren't listed ($0 and $1 challenges) show up in v5
 - Submissions on code for multiple submissions show up, as we talked about.

Everything else exactly matches at first glance.
Fixed a couple problems with the sync and it has caught up and run. 

I also removed the duplicate challenges you found in #215 

And I haven't seen any issues with duplicate registrants #234 

Please confirm

**Comment by SathyaJayabal** [comment] 2020-07-29 03:30
@rootelement , i still see empty registrants list on this challenge
https://beta-community-app.topcoder.com/challenges/2ce9c4cb-b4ce-4aa5-9807-d3f655860732?tab=registrants
<img width="1440" alt="Screenshot 2020-07-29 at 8 59 45 AM" src="https://user-images.githubusercontent.com/58783823/88753480-df8c8e00-d179-11ea-9f1f-883aa0864954.png">

**Comment by SathyaJayabal** [comment] 2020-07-29 05:50
@rootelement , one more
https://beta-community-app.topcoder.com/challenges/0ea10b6f-c089-457b-8c08-b01be006b25e?tab=registrants
<img width="1440" alt="Screenshot 2020-07-29 at 11 19 29 AM" src="https://user-images.githubusercontent.com/58783823/88761768-6ac34f00-d18d-11ea-95cd-dd3caf3f0ec5.png">

**Comment by SathyaJayabal** [comment] 2020-07-29 07:25
one more case where registrants data is missing
https://beta-community-app.topcoder.com/challenges/27d092fa-167c-4a0c-b6ee-b07ace75c159?tab=registrants
https://www.topcoder.com/challenges/30131970?tab=registrants
<img width="1440" alt="Screenshot 2020-07-29 at 12 35 03 PM" src="https://user-images.githubusercontent.com/58783823/88767951-f9d56480-d197-11ea-81a2-e25c821c7a12.png">
<img width="1440" alt="Screenshot 2020-07-29 at 12 35 12 PM" src="https://user-images.githubusercontent.com/58783823/88768431-b6c7c100-d198-11ea-91a2-1dc75ddb321b.png">

**Comment by SathyaJayabal** [comment] 2020-08-06 03:31
I believe this is fixed with the latest migration.

**Closed by SathyaJayabal** 2020-08-06 03:31 UTC
Labels: Must-fix-before-v5-release, P0, community-app-integration
